### PR TITLE
Adding integration tests for GETREF and SLICE over JSON.

### PR DESCRIPTION
**Pull request by jsanda**
This commit also includes a change to IntraService. The SET op typically looks
like,

``` javascript
{
  "type": "SET",
  "op": {
    "rowkey": "row_key1",
    "name": "column1",
    "value": "value1"
  }
}
```

but when using GETREF it looks like,

``` javascript
{
  "type": "SET",
  "op": {
    "rowkey": "getref_test",
    "name": "col3",
    "value": {
      "type": "GETREF",
      "op": {
        "resultref": 4,
        "wanted": "value"
      }
    }
  }
}
```

In this case the value attribute references a nested GETREF op. With the
default JSON deserialization, the nested GETREF is getted deserialized as a
Map instead of a IntraOp. I have added logic in InstraService to handle the
nested map.

### CODE REVIEW

**Comment by jsanda** [comment]
It may make more sense to implement a custom JSON deserializer to handled the nested GETREF. I do not have any experience doing that with Jackson though; so, my change seemed like a reasonable solution for the interim.

**Comment by zznate** [comment]
Hrm - might have merged these out of order - @jsanda, can I get you to rebase? Otherwise, I agree, this seems like a reasonable approach. When we get a little closer, we can always throw up the Batsignal™ for cowtowncoder - he's a good dude and likes helping with performance-related Jackson stuff.

**Comment by edwardcapriolo** [comment]
This is overall a good change. This is the only place in the code that has a nested IntraOp. Really now this function can be done with one of the Processor Interfaces but I think it is good to keep. @jsanda Now that you have done this you should be able to remove ResRef from intraOp this would finish the code cleanup.

**Comment by jsanda** [comment]
re: rebase. Sure I when I get a chance this afternoon I will do so. Rebase
off of master?

@edwardcarpriolo Just want to make sure I understand. I see
Operations.getResRefOp which creates a GETREF. Are you saying we can get
rid of Operations.getResRefOp or altogether get rid of the GETREF type?

On Thu, Feb 7, 2013 at 12:16 PM, edwardcapriolo notifications@github.comwrote:

> This is overall a good change. This is the only place in the code that has
> a nested IntraOp. Really now this function can be done with one of the
> Processor Interfaces but I think it is good to keep. @jsandahttps://github.com/jsandaNow that you have done this you should be able to remove ResRef from
> intraOp this would finish the code cleanup.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zznate/intravert-ug/pull/80#issuecomment-13247268.

## 
- John

**Comment by edwardcapriolo** [comment]
Yes rebase off master. I made some changes that messed you up. Sorry. 

So.... the problem with Operations.getResRefOp is that it returns an Operation not a map. So that is not so bad that will be the only static method there that does not return an IntraOp.
GETREF type should be a candidate for removal then since it would no longer be an op. 

I am not sure what is the 100% correct course of action, becuase GetRef is an odd case. Do the refactor that makes sense to you and then I will look it over. If my suggestions involve drastic changes we can continue going with your patch, as long as all tests pass I am happy.

**Comment by jsanda** [comment]
I went ahead and rebased. I had to resolve a couple conflicts in import statements. I ran all the tests before committing/pushing. Please review though to make sure I didn't screw anything up. Thanks.

**Pull request merged**
