### PR TITLE
This is for issue #8

### PR DESCRIPTION
**Pull request by edwardcapriolo**
Removed the usergrid bits and made just one simple client. Sorry I do not know how to link this pull request to the issue,

### CODE REVIEW

**Comment by edwardcapriolo** [comment]
Also added a default handler nor related to issue 8

**Comment by boneill42** [comment]
I was just giving this a spin, and ran into:
org/vertx/java/core/Handler : Unsupported major.minor version 51.0

Are we targeting JDK 6 or 7?  Some of the vertx components are targeting JDK 7.  Specifically, core looks like it is compiled with JDK 7:
https://github.com/vert-x/vert.x/blob/master/build.gradle

The vertx-maven-plugin is also using JDK 7:
https://github.com/rhart/vertx-maven-plugin/blob/master/pom.xml

This ended up giving me some trouble since our pom is using JDK 1.6.  
Should we up ours to 7 and standardize on JDK 7?

**Comment by zznate** [comment]
Should be jdk7 due to 'invokedynamic' usage for all the polyglot stuff.

**Comment by boneill42** [comment]
Cool.  Let's up that in the compiler plugin in the pom.

-brian

---

Brian O'Neill
Lead Architect, Software Development
Health Market Science
The Science of Better Results
2700 Horizon Drive € King of Prussia, PA € 19406
M: 215.588.6024 € @boneill42 http://www.twitter.com/boneill42   €
healthmarketscience.com

This information transmitted in this email message is for the intended
recipient only and may contain confidential and/or privileged material. If
you received this email in error and are not the intended recipient, or the
person responsible to deliver it to the intended recipient, please contact
the sender at the email above and delete this email and any attachments and
destroy any copies thereof. Any review, retransmission, dissemination,
copying or other use of, or taking any action in reliance upon, this
information by persons or entities other than the intended recipient is
strictly prohibited.

From:  Nate McCall notifications@github.com
Reply-To:  zznate/intravert-ug
<reply+i-8582357-d41c91529212f66eb4d55f14fa31ec440c5c0940-897229@reply.githu
b.com>
Date:  Monday, November 26, 2012 9:35 PM
To:  zznate/intravert-ug intravert-ug@noreply.github.com
Cc:  Brian O'Neill bone@alumni.brown.edu
Subject:  Re: [intravert-ug] This is for issue #8 (#9)

Should be jdk7 due to 'invokedynamic' usage for all the polyglot stuff.

 ‹
 Reply to this email directly or view it on GitHub
https://github.com/zznate/intravert-ug/pull/9#issuecomment-10744053 .

**Pull request merged**
