### PR TITLE
Ok here is the dynamic code for a scanner, you can create a scanner it d...

### PR DESCRIPTION
**Pull request by edwardcapriolo**
...oes not work yet..

### CODE REVIEW

**Comment by jsanda** [comment]
I haven't had a chance to look very closely but what is the difference between a filter and a scanner?

**Comment by edwardcapriolo** [comment]
Scanners are going to be like hbase scanners, on the client side they are going to be iterable. For example if you have a row with 1,000,000 columns and you want to want through it. Currently now clients have to page through get_range_slices, and transmit all 1,000,000 columns to the client. In this way filtering will be applied server side. 
Rows will be returned and the client has a simple iteration method. It looks something like this:

Scan s = = new Scan(Mykeyspace, mycolumnfamily, startrow, endrow, start column, end column, filter f { only people from ny});
ScanResults sr = ic.scan();

while (scanResults.hasNext() ){
  row = scan.next();
  println row;
  if (row = danger)
   continue;
}

Think of itlike streaming a large column, while it is being filtered (optionally) server side.

**Comment by edwardcapriolo** [comment]
Though in my explanation I am wondering if the process could be implemented totally as a client side abstraction.

**Comment by edwardcapriolo** [comment]
I added this... https://github.com/zznate/intravert-ug/issues/98 . while thinking on this topic

**Comment by edwardcapriolo** [comment]
There is some subtle differences scanners have more "flow control". since they can opt out, etc etc.

**Pull request merged**
