### PR TITLE
Virgil rest handler

### PR DESCRIPTION
**Pull request by zznate**

### CODE REVIEW

**Comment by edwardcapriolo** [comment]
I am not really a mockito fan... but I can live with it. I guess. Im on the fence about it. What is your time line for this? This was in the 1.0 talks but is ittoo late in the game at this point?

**Comment by zznate** [comment]
Don't think so. There are not terribly many moving parts. Can just as easily be in there but "disabled" since it will be a different handler as well.

**Comment by boneill42** [comment]
If you want, I may be able to crank this out this week.  Let me know if you want me to pick it up.

**Comment by zznate** [comment]
\o/
That would be awesome. Let's pull this in, so we can consolidate IntraHandlerJson and clean up the event-bus delegation a bit. 
That cool with you @edwardcapriolo ?

**Comment by edwardcapriolo** [comment]
cleanup up IntraHandlerJson should be its own issue not included with this. I think this is a separate handler / endpoint? That should be a fairly simple refactor.

**Comment by edwardcapriolo** [comment]
As for virgil it makes huge sense. Its a big win virgil users will get a ton more performance. IntraVert becomes a more attractive add in. Win/Win.

**Comment by zznate** [comment]
Agreed about separate issue. I'll make that now. Edit: adding link to #142

**Comment by boneill42** [comment]
@zznate : I like what you did with the REST design.

Quick question... since I'm about to implement createKeyspace for REST.

I'm torn...

Think we should have a java class for each HTTP method.  e.g. 
GetColumnFamilyHandler
PutColumnFamilyHandler
…

Or just case/if statements within each handler. e.g.
CollumnFamilyHeader
    public void handleRequestAsync(final HttpServerRequest request, Buffer buffer) {
       if (request.method == "GET") {  
          Operations.listColumnFamilies();
       } else if (request.method == "POST"){
          Operations.createKeyspace()
        }

I"m leaning towards a class for each, but there might be significant overlap/re-use between each (especially when we get to response transformation), and introducing a second level of inheritance doesn't feel right.

**Comment by edanuff** [comment]
You may want to consider a single class per handler with GET/PUT/POST/DELETE mapping to methods in it.  You often see in REST frameworks an abstract base handler class that has a default implementation of the handle() method that dispatches to handleGet(), handlePost(), etc. methods so you can just override handleGet() if thats all you want to do.

**Comment by boneill42** [comment]
Sold.  (Just got createKeyspace working with that model)  It looks good.  I'll push to my repo in a few minutes.

**Comment by boneill42** [comment]
https://github.com/boneill42/intravert-ug/blob/virgil-rest-handler/src/main/java/org/usergrid/vx/handler/rest/ColumnFamilyMetaHandler.java

**Pull request merged**
